# Generated by Django 4.0.1 on 2022-02-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.CharField(max_length=10)),
                ('highest_Qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('pan', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('emergency_contact_number', models.IntegerField()),
                ('nationality', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_image', models.CharField(blank=True, max_length=500, null=True)),
                ('documents', models.CharField(blank=True, max_length=500, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=10, null=True)),
                ('last_working_date', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
