# Generated by Django 4.0.2 on 2022-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeeregistration_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeregistration',
            name='_photo',
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='photo_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
