# Generated by Django 4.0.2 on 2022-03-01 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('values', models.TextField(max_length=100)),
                ('display_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('leave_type', models.IntegerField()),
                ('from_Date', models.DateField()),
                ('to_Date', models.DateField()),
                ('leave_applied_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.IntegerField(default=10)),
                ('casual', models.IntegerField(default=10)),
                ('earned', models.IntegerField(default=10)),
                ('sick', models.IntegerField(default=10)),
                ('bereavement', models.IntegerField(default=5)),
                ('optional', models.IntegerField(default=2)),
                ('maternity', models.IntegerField(default=180)),
                ('paternity', models.IntegerField(default=30)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
