# Generated by Django 4.0.2 on 2022-03-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='values',
            new_name='leave_type',
        ),
    ]
