# Generated by Django 4.0.2 on 2022-03-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagement', '0004_holidaylist_is_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaylist',
            name='is_weekend',
        ),
    ]
